@Smoke @agreements
Feature: AGR_006_ValidateAgreementsAPI_CTA
	Description: Validate GET, POST, PUT and PATCH Requests for CTA Agreements API 


          ## ******************* POST REQUEST **************************************
Scenario: AGR_006_01_ValidateAgreementsAPI_CTA-TypeOfTrail-IndustrySponsored_PostRequest       
        Given I Set UP URL For APIs with Endpoint as "/api/agreements"
        And I Retrieve Token Key for API
        And I Validate Expiry for API Token
         When I generate payload of Agreements for Post request for CTA API
        | title                  | firstDraftTobeGeneratedInternally | principalInvestigator/hrn | primaryContact/hrn  | agreementType/hrn             | responsibleUnit/hrn | counterParties/0/organization/hrn | counterParties/0/person/hrn | agreementTypeData/typeOfTrial/hrn         | agreementTypeData/phaseOfStudy/hrn          | agreementTypeData/sponsorProtocolNumber | agreementTypeData/protocolTitle | agreementTypeData/protocolDocument/url                            | agreementTypeData/consentFormsDocuments/0/url                     | agreementTypeData/isReimbursementTobeProvided | agreementTypeData/willUseCro | agreementTypeData/cro/hrn | agreementTypeData/croOther | agreementTypeData/croContactsOther/1/person/hrn | agreementTypeData/croContactsOther/2/person/hrn | agreementTypeData/croContactsOther/2/contactName | agreementTypeData/croContactsOther/2/contactPhone | agreementTypeData/croContactsOther/2/contactEmail | agreementTypeData/croContactPrimary/person/hrn | agreementTypeData/doesThisInvolveSubrecipients | agreementTypeData/subrecipientsOrganizations  | agreementTypeData/ctaMaterials/0/materialType/hrn | agreementTypeData/ctaMaterials/0/useInTrial/hrn | agreementTypeData/ctaMaterials/0/provider | agreementTypeData/ctaMaterials/0/materialDescription | agreementTypeData/doesThisInvolveOtherMaterials | agreementTypeData/ctaMaterialsOther/0/materialType/hrn | agreementTypeData/ctaMaterialsOther/0/provider | agreementTypeData/ctaMaterialsOther/0/materialDescription | agreementTypeData/isStudyPartOfCooperativeGroup |
        | Agreement MTA Test 514 | true                              | hrn:hrs:persons:801       | hrn:hrs:persons:301 | hrn:hrs:lists:agrmt-types/CTA | hrn:hrs:orgs:309    | hrn:hrs:orgs:3                    | hrn:hrs:persons:301         | hrn:hrs:lists:agrmt-cta-type-trial/ind-sp | hrn:hrs:lists:agrmt-cta-phase-study/phase-1 | FF720W                                  | Wyeth ZZ784                     | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | false                                         | true                         | hrn:hrs:orgs:33           | test                       | hrn:hrs:persons:801                             | hrn:hrs:persons:811                             | contact2                                         | 044-1234567                                       | contactEmail@huron.com                            | hrn:hrs:persons:801                            | null                                         | null                                            | hrn:hrs:lists:agrmt-cta-material-type/other       | hrn:hrs:lists:agrmt-cta-use-in-trial/research   | provider1                                 | materialDescription12                                | true                                            | hrn:hrs:lists:agrmt-cta-material-type-other/other      | provider1                                      | materialDescription                                       | true                                            |
         When I perform Post request for Agreements
        Then I Validate new record after post request
        Then I perform Get request and verify the resource created
      And I Validate "agreementType/hrn" attribute for Agreements
      And I Validate "agreementTypeData/typeOfTrial/hrn" attribute for Agreements
        And I Validate "agreementTypeData/phaseOfStudy/hrn" attribute for Agreements
        And I Validate "agreementTypeData/sponsorProtocolNumber" attribute for Agreements
        And I Validate "agreementTypeData/protocolTitle" attribute for Agreements
        And I Validate "agreementTypeData/isReimbursementTobeProvided" attribute for Agreements
        And I Validate "agreementTypeData/willUseCro" attribute for Agreements
        And I Validate "agreementTypeData/croOther" attribute for Agreements
       And I Validate "agreementTypeData/croContactsOther/1/person/hrn" attribute for Agreements
       And I Validate "agreementTypeData/croContactPrimary/person/hrn" attribute for Agreements
       And I Validate "agreementTypeData/ctaMaterials/0/materialType/hrn" attribute for Agreements
       And I Validate "agreementTypeData/ctaMaterials/0/useInTrial/hrn" attribute for Agreements
       And I Validate "agreementTypeData/doesThisInvolveOtherMaterials" attribute for Agreements
       And I Validate "agreementTypeData/isStudyPartOfCooperativeGroup" attribute for Agreements


             ## ******************* PUT REQUEST *********************************
Scenario:  AGR_006_02_ValidateAgreementsAPI_CTA-TypeOfTrail-IndustrySponsored_PutRequest 
     Given I Set UP URL For APIs with Endpoint as "/api/agreements"
     Then I retrieve data using unique key received after successful Post Request
      When I update payload of Agreements for put request
     | agreementType/hrn                  | agreementTypeData/typeOfTrial/hrn         | agreementTypeData/phaseOfStudy/hrn          | agreementTypeData/sponsorProtocolNumber | agreementTypeData/protocolTitle | agreementTypeData/protocolDocument/url                            | agreementTypeData/consentFormsDocuments/0/url                     | agreementTypeData/isReimbursementTobeProvided | agreementTypeData/willUseCro | agreementTypeData/cro/hrn | agreementTypeData/croOther | agreementTypeData/croContactsOther/1/person/hrn | agreementTypeData/croContactsOther/2/person/hrn | agreementTypeData/croContactsOther/2/contactName | agreementTypeData/croContactsOther/2/contactPhone | agreementTypeData/croContactsOther/2/contactEmail | agreementTypeData/croContactPrimary/person/hrn | agreementTypeData/doesThisInvolveSubrecipients | agreementTypeData/subrecipientsOrganizations  | agreementTypeData/ctaMaterials/0/materialType/hrn | agreementTypeData/ctaMaterials/0/useInTrial/hrn | agreementTypeData/ctaMaterials/0/provider | agreementTypeData/ctaMaterials/0/materialDescription | agreementTypeData/doesThisInvolveOtherMaterials | agreementTypeData/ctaMaterialsOther/0/materialType/hrn | agreementTypeData/ctaMaterialsOther/0/provider | agreementTypeData/ctaMaterialsOther/0/materialDescription | agreementTypeData/isStudyPartOfCooperativeGroup |
     | hrn:hrs:lists:agrmt-types/CTA      | hrn:hrs:lists:agrmt-cta-type-trial/ind-sp | hrn:hrs:lists:agrmt-cta-phase-study/phase-2 | FF720W                                  | Wyeth ZZ784                     | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | false                                         | true                         | hrn:hrs:orgs:33           | test                       | hrn:hrs:persons:801                             | hrn:hrs:persons:811                             | contact2                                         | 044-1234567                                       | contactEmail@huron.com                            | hrn:hrs:persons:801                            | null                                         | null                                            | hrn:hrs:lists:agrmt-cta-material-type/device       | hrn:hrs:lists:agrmt-cta-use-in-trial/standard-of-care   | provider1                                 | materialDescription12                                | true                                            | hrn:hrs:lists:agrmt-cta-material-type-other/equipment     | provider1                                      | materialDescription                                       | true                                |
     When I perform Put request for Agreements
	 Then I validate status code for Put requests
      And I Validate "agreementType/hrn" attribute for Agreements
      And I Validate "agreementTypeData/typeOfTrial/hrn" attribute for Agreements
        And I Validate "agreementTypeData/phaseOfStudy/hrn" attribute for Agreements
        And I Validate "agreementTypeData/sponsorProtocolNumber" attribute for Agreements
        And I Validate "agreementTypeData/protocolTitle" attribute for Agreements
        And I Validate "agreementTypeData/isReimbursementTobeProvided" attribute for Agreements
        And I Validate "agreementTypeData/willUseCro" attribute for Agreements
        And I Validate "agreementTypeData/croOther" attribute for Agreements
       And I Validate "agreementTypeData/croContactsOther/1/person/hrn" attribute for Agreements
       And I Validate "agreementTypeData/croContactPrimary/person/hrn" attribute for Agreements
       And I Validate "agreementTypeData/ctaMaterials/0/materialType/hrn" attribute for Agreements
       And I Validate "agreementTypeData/ctaMaterials/0/useInTrial/hrn" attribute for Agreements
       And I Validate "agreementTypeData/doesThisInvolveOtherMaterials" attribute for Agreements
       And I Validate "agreementTypeData/isStudyPartOfCooperativeGroup" attribute for Agreements

         

         ## ********************* PATCH REQUEST *********************************
Scenario: AGR_006_03_ValidateAgreementsAPI_CTA-TypeOfTrail-IndustrySponsored_PatchRequest

   Given I Set UP URL For APIs with Endpoint as "/api/agreements"
    When I retrieve data using unique key by Get Request for Agreements
    | hrn      |
    | hrn:hrs:agreements:797 |
    When I create payload for Patch request
     | agreementType/hrn                      | agreementTypeData/typeOfTrial/hrn         | agreementTypeData/phaseOfStudy/hrn          | agreementTypeData/sponsorProtocolNumber | agreementTypeData/protocolTitle | agreementTypeData/protocolDocument/url                            | agreementTypeData/consentFormsDocuments/0/url                     | agreementTypeData/isReimbursementTobeProvided | agreementTypeData/willUseCro | agreementTypeData/cro/hrn | agreementTypeData/croOther | agreementTypeData/croContactsOther/1/person/hrn | agreementTypeData/croContactsOther/2/person/hrn | agreementTypeData/croContactsOther/2/contactName | agreementTypeData/croContactsOther/2/contactPhone | agreementTypeData/croContactsOther/2/contactEmail | agreementTypeData/croContactPrimary/person/hrn | agreementTypeData/doesThisInvolveSubrecipients | agreementTypeData/subrecipientsOrganizations  | agreementTypeData/ctaMaterials/0/materialType/hrn | agreementTypeData/ctaMaterials/0/useInTrial/hrn | agreementTypeData/ctaMaterials/0/provider | agreementTypeData/ctaMaterials/0/materialDescription | agreementTypeData/doesThisInvolveOtherMaterials | agreementTypeData/ctaMaterialsOther/0/materialType/hrn | agreementTypeData/ctaMaterialsOther/0/provider | agreementTypeData/ctaMaterialsOther/0/materialDescription | agreementTypeData/isStudyPartOfCooperativeGroup |
          | hrn:hrs:lists:agrmt-types/CTA      | hrn:hrs:lists:agrmt-cta-type-trial/ind-sp | hrn:hrs:lists:agrmt-cta-phase-study/phase-3 | FF720W                                  | Wyeth ZZ784                     | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | false                                         | true                         | hrn:hrs:orgs:33           | test                       | hrn:hrs:persons:801                             | hrn:hrs:persons:811                             | contact2                                         | 044-1234567                                       | contactEmail@huron.com                            | hrn:hrs:persons:801                            | null                                         | null                                            | hrn:hrs:lists:agrmt-cta-material-type/drug      | hrn:hrs:lists:agrmt-cta-use-in-trial/research   | provider1                                 | materialDescription12                                | true                                            | hrn:hrs:lists:agrmt-cta-material-type-other/other    | provider1                                      | materialDescription                                       | true                                            |
   	When I perform Patch request for Agreements
	Then I validate status code for Patch request
      And I Validate "agreementType/hrn" attribute for Agreements
      And I Validate "agreementTypeData/typeOfTrial/hrn" attribute for Agreements
        And I Validate "agreementTypeData/phaseOfStudy/hrn" attribute for Agreements
        And I Validate "agreementTypeData/sponsorProtocolNumber" attribute for Agreements
        And I Validate "agreementTypeData/protocolTitle" attribute for Agreements
        And I Validate "agreementTypeData/isReimbursementTobeProvided" attribute for Agreements
        And I Validate "agreementTypeData/willUseCro" attribute for Agreements
        And I Validate "agreementTypeData/croOther" attribute for Agreements
       And I Validate "agreementTypeData/croContactsOther/1/person/hrn" attribute for Agreements
       And I Validate "agreementTypeData/croContactPrimary/person/hrn" attribute for Agreements
       And I Validate "agreementTypeData/ctaMaterials/0/materialType/hrn" attribute for Agreements
       And I Validate "agreementTypeData/ctaMaterials/0/useInTrial/hrn" attribute for Agreements
       And I Validate "agreementTypeData/doesThisInvolveOtherMaterials" attribute for Agreements
       And I Validate "agreementTypeData/isStudyPartOfCooperativeGroup" attribute for Agreements

         
          ## ******************* POST REQUEST **************************************
Scenario: AGR_006_04_ValidateAgreementsAPI_CTA-TypeOfTrail-InitiatedAtOurInstitution_PostRequest       
        Given I Set UP URL For APIs with Endpoint as "/api/agreements"
        And I Retrieve Token Key for API
        And I Validate Expiry for API Token
         When I generate payload of Agreements for Post request for CTA API
        | title                  | firstDraftTobeGeneratedInternally | principalInvestigator/hrn | primaryContact/hrn  | agreementType/hrn             | responsibleUnit/hrn | counterParties/0/organization/hrn | counterParties/0/person/hrn | agreementTypeData/typeOfTrial/hrn               | agreementTypeData/phaseOfStudy/hrn          | agreementTypeData/sponsorProtocolNumber | agreementTypeData/protocolTitle | agreementTypeData/protocolDocument/url                            | agreementTypeData/consentFormsDocuments/0/url                     | agreementTypeData/isReimbursementTobeProvided | agreementTypeData/willUseCro | agreementTypeData/cro/hrn | agreementTypeData/croOther | agreementTypeData/croContactsOther/1/person/hrn | agreementTypeData/croContactsOther/2/person/hrn | agreementTypeData/croContactsOther/2/contactName | agreementTypeData/croContactsOther/2/contactPhone | agreementTypeData/croContactsOther/2/contactEmail | agreementTypeData/croContactPrimary/person/hrn | agreementTypeData/doesThisInvolveSubrecipients | agreementTypeData/subrecipientsOrganizations/0/organization/hrn | agreementTypeData/ctaMaterials/0/materialType/hrn | agreementTypeData/ctaMaterials/0/useInTrial/hrn | agreementTypeData/ctaMaterials/0/provider | agreementTypeData/ctaMaterials/0/materialDescription | agreementTypeData/doesThisInvolveOtherMaterials | agreementTypeData/ctaMaterialsOther/0/materialType/hrn | agreementTypeData/ctaMaterialsOther/0/provider | agreementTypeData/ctaMaterialsOther/0/materialDescription | agreementTypeData/isStudyPartOfCooperativeGroup |
        | Agreement MTA Test 514 | true                              | hrn:hrs:persons:801       | hrn:hrs:persons:301 | hrn:hrs:lists:agrmt-types/CTA | hrn:hrs:orgs:309    | hrn:hrs:orgs:3                    | hrn:hrs:persons:301         | hrn:hrs:lists:agrmt-cta-type-trial/inv-init-inst | hrn:hrs:lists:agrmt-cta-phase-study/phase-4 | null                               | Wyeth ZZ784                     | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | false                                         | true                         | hrn:hrs:orgs:33           | test                       | hrn:hrs:persons:801                             | hrn:hrs:persons:811                             | contact2                                         | 044-1234567                                       | contactEmail@huron.com                            | hrn:hrs:persons:801                            | true                                       | hrn:hrs:orgs:3                                    | hrn:hrs:lists:agrmt-cta-material-type/device      | hrn:hrs:lists:agrmt-cta-use-in-trial/standard-of-care  | provider1                                 | materialDescription12                                | true                                            | hrn:hrs:lists:agrmt-cta-material-type-other/equipment    | provider1                                      | materialDescription                                       | true                                            |
         When I perform Post request for Agreements
        Then I Validate new record after post request
        Then I perform Get request and verify the resource created
      And I Validate "agreementType/hrn" attribute for Agreements
      And I Validate "agreementTypeData/typeOfTrial/hrn" attribute for Agreements
        And I Validate "agreementTypeData/phaseOfStudy/hrn" attribute for Agreements
        And I Validate "agreementTypeData/sponsorProtocolNumber" attribute for Agreements
        And I Validate "agreementTypeData/protocolTitle" attribute for Agreements
        And I Validate "agreementTypeData/isReimbursementTobeProvided" attribute for Agreements
        And I Validate "agreementTypeData/willUseCro" attribute for Agreements
        And I Validate "agreementTypeData/croOther" attribute for Agreements
       And I Validate "agreementTypeData/croContactsOther/1/person/hrn" attribute for Agreements
       And I Validate "agreementTypeData/croContactPrimary/person/hrn" attribute for Agreements
       And I Validate "agreementTypeData/ctaMaterials/0/materialType/hrn" attribute for Agreements
       And I Validate "agreementTypeData/ctaMaterials/0/useInTrial/hrn" attribute for Agreements
       And I Validate "agreementTypeData/doesThisInvolveOtherMaterials" attribute for Agreements
       And I Validate "agreementTypeData/doesThisInvolveSubrecipients" attribute for Agreements
        And I Validate "agreementTypeData/subrecipientsOrganizations/0/organization/hrn" attribute for Agreements
       And I Validate "agreementTypeData/isStudyPartOfCooperativeGroup" attribute for Agreements


          ## ******************* PUT REQUEST *********************************
Scenario:  AGR_006_05_ValidateAgreementsAPI_CTA-TypeOfTrail-InitiatedAtOurInstitution_PutRequest 
     Given I Set UP URL For APIs with Endpoint as "/api/agreements"
     Then I retrieve data using unique key received after successful Post Request
      When I update payload of Agreements for put request
      | agreementType/hrn              | agreementTypeData/typeOfTrial/hrn               | agreementTypeData/phaseOfStudy/hrn          | agreementTypeData/sponsorProtocolNumber | agreementTypeData/protocolTitle | agreementTypeData/protocolDocument/url                            | agreementTypeData/consentFormsDocuments/0/url                 | agreementTypeData/isReimbursementTobeProvided | agreementTypeData/willUseCro | agreementTypeData/cro/hrn | agreementTypeData/croOther | agreementTypeData/croContactsOther/1/person/hrn | agreementTypeData/croContactsOther/2/person/hrn | agreementTypeData/croContactsOther/2/contactName | agreementTypeData/croContactsOther/2/contactPhone | agreementTypeData/croContactsOther/2/contactEmail | agreementTypeData/croContactPrimary/person/hrn | agreementTypeData/doesThisInvolveSubrecipients | agreementTypeData/subrecipientsOrganizations/0/organization/hrn | agreementTypeData/ctaMaterials/0/materialType/hrn | agreementTypeData/ctaMaterials/0/useInTrial/hrn | agreementTypeData/ctaMaterials/0/provider | agreementTypeData/ctaMaterials/0/materialDescription | agreementTypeData/doesThisInvolveOtherMaterials | agreementTypeData/ctaMaterialsOther/0/materialType/hrn | agreementTypeData/ctaMaterialsOther/0/provider | agreementTypeData/ctaMaterialsOther/0/materialDescription | agreementTypeData/isStudyPartOfCooperativeGroup |
 | hrn:hrs:lists:agrmt-types/CTA     | hrn:hrs:lists:agrmt-cta-type-trial/inv-init-inst | hrn:hrs:lists:agrmt-cta-phase-study/phase-otr | null                               | Wyeth ZZ784                     | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | false                                         | true                         | hrn:hrs:orgs:33           | test                       | hrn:hrs:persons:801                             | hrn:hrs:persons:811                             | contact2                                         | 044-1234567                                       | contactEmail@huron.com                            | hrn:hrs:persons:801                            | true                                       | hrn:hrs:orgs:3                                    | hrn:hrs:lists:agrmt-cta-material-type/drug     | hrn:hrs:lists:agrmt-cta-use-in-trial/research  | provider1                                 | materialDescription12                                | true                                            | hrn:hrs:lists:agrmt-cta-material-type-other/equipment    | provider1                                      | materialDescription                                       | true                                            |
     When I perform Put request for Agreements
	 Then I validate status code for Put requests
      And I Validate "agreementType/hrn" attribute for Agreements
      And I Validate "agreementTypeData/typeOfTrial/hrn" attribute for Agreements
        And I Validate "agreementTypeData/phaseOfStudy/hrn" attribute for Agreements
        And I Validate "agreementTypeData/sponsorProtocolNumber" attribute for Agreements
        And I Validate "agreementTypeData/protocolTitle" attribute for Agreements
        And I Validate "agreementTypeData/isReimbursementTobeProvided" attribute for Agreements
        And I Validate "agreementTypeData/willUseCro" attribute for Agreements
        And I Validate "agreementTypeData/croOther" attribute for Agreements
       And I Validate "agreementTypeData/croContactsOther/1/person/hrn" attribute for Agreements
       And I Validate "agreementTypeData/croContactPrimary/person/hrn" attribute for Agreements
       And I Validate "agreementTypeData/ctaMaterials/0/materialType/hrn" attribute for Agreements
       And I Validate "agreementTypeData/ctaMaterials/0/useInTrial/hrn" attribute for Agreements
       And I Validate "agreementTypeData/doesThisInvolveOtherMaterials" attribute for Agreements
        And I Validate "agreementTypeData/doesThisInvolveSubrecipients" attribute for Agreements
        And I Validate "agreementTypeData/subrecipientsOrganizations/0/organization/hrn" attribute for Agreements
       And I Validate "agreementTypeData/isStudyPartOfCooperativeGroup" attribute for Agreements

        
          ## ******************* POST REQUEST **************************************
Scenario: AGR_006_06_ValidateAgreementsAPI_CTA-TypeOfTrail-InvestigatorInitiatedAtAnotherInstitution_PostRequest       
        Given I Set UP URL For APIs with Endpoint as "/api/agreements"
        And I Retrieve Token Key for API
        And I Validate Expiry for API Token
         When I generate payload of Agreements for Post request for CTA API
        | title                  | firstDraftTobeGeneratedInternally | principalInvestigator/hrn | primaryContact/hrn  | agreementType/hrn             | responsibleUnit/hrn | counterParties/0/organization/hrn | counterParties/0/person/hrn | agreementTypeData/typeOfTrial/hrn               | agreementTypeData/phaseOfStudy/hrn          | agreementTypeData/sponsorProtocolNumber | agreementTypeData/protocolTitle | agreementTypeData/protocolDocument/url                            | agreementTypeData/consentFormsDocuments/0/url                     | agreementTypeData/isReimbursementTobeProvided | agreementTypeData/willUseCro | agreementTypeData/cro/hrn | agreementTypeData/croOther | agreementTypeData/croContactsOther/1/person/hrn | agreementTypeData/croContactsOther/2/person/hrn | agreementTypeData/croContactsOther/2/contactName | agreementTypeData/croContactsOther/2/contactPhone | agreementTypeData/croContactsOther/2/contactEmail | agreementTypeData/croContactPrimary/person/hrn | agreementTypeData/doesThisInvolveSubrecipients | agreementTypeData/subrecipientsOrganizations | agreementTypeData/ctaMaterials/0/materialType/hrn | agreementTypeData/ctaMaterials/0/useInTrial/hrn | agreementTypeData/ctaMaterials/0/provider | agreementTypeData/ctaMaterials/0/materialDescription | agreementTypeData/doesThisInvolveOtherMaterials | agreementTypeData/ctaMaterialsOther/0/materialType/hrn | agreementTypeData/ctaMaterialsOther/0/provider | agreementTypeData/ctaMaterialsOther/0/materialDescription | agreementTypeData/isStudyPartOfCooperativeGroup |
        | Agreement MTA Test 514 | true                              | hrn:hrs:persons:801       | hrn:hrs:persons:301 | hrn:hrs:lists:agrmt-types/CTA | hrn:hrs:orgs:309    | hrn:hrs:orgs:3                    | hrn:hrs:persons:301         | hrn:hrs:lists:agrmt-cta-type-trial/inv-init-otr-inst | hrn:hrs:lists:agrmt-cta-phase-study/phase-registry | Z123EF                            | Wyeth ZZ784                     | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | false                                         | true                         | hrn:hrs:orgs:33           | test                       | hrn:hrs:persons:801                             | hrn:hrs:persons:811                             | contact2                                         | 044-1234567                                       | contactEmail@huron.com                            | hrn:hrs:persons:801                            | null                                  | null                                | hrn:hrs:lists:agrmt-cta-material-type/device      | hrn:hrs:lists:agrmt-cta-use-in-trial/standard-of-care  | provider1                                 | materialDescription12                                | true                                            | hrn:hrs:lists:agrmt-cta-material-type-other/equipment    | provider1                                      | materialDescription                                       | true                                            |
         When I perform Post request for Agreements
        Then I Validate new record after post request
        Then I perform Get request and verify the resource created
      And I Validate "agreementType/hrn" attribute for Agreements
      And I Validate "agreementTypeData/typeOfTrial/hrn" attribute for Agreements
        And I Validate "agreementTypeData/phaseOfStudy/hrn" attribute for Agreements
        And I Validate "agreementTypeData/sponsorProtocolNumber" attribute for Agreements
        And I Validate "agreementTypeData/protocolTitle" attribute for Agreements
        And I Validate "agreementTypeData/isReimbursementTobeProvided" attribute for Agreements
        And I Validate "agreementTypeData/willUseCro" attribute for Agreements
        And I Validate "agreementTypeData/croOther" attribute for Agreements
       And I Validate "agreementTypeData/croContactsOther/1/person/hrn" attribute for Agreements
       And I Validate "agreementTypeData/croContactPrimary/person/hrn" attribute for Agreements
       And I Validate "agreementTypeData/ctaMaterials/0/materialType/hrn" attribute for Agreements
       And I Validate "agreementTypeData/ctaMaterials/0/useInTrial/hrn" attribute for Agreements
       And I Validate "agreementTypeData/doesThisInvolveOtherMaterials" attribute for Agreements
       And I Validate "agreementTypeData/isStudyPartOfCooperativeGroup" attribute for Agreements


          ## ******************* PUT REQUEST *********************************
Scenario:  AGR_006_07_ValidateAgreementsAPI_CTA-TypeOfTrail-InvestigatorInitiatedAtAnotherInstitution_PutRequest 
     Given I Set UP URL For APIs with Endpoint as "/api/agreements"
     Then I retrieve data using unique key received after successful Post Request
      When I update payload of Agreements for put request
      | agreementType/hrn               | agreementTypeData/typeOfTrial/hrn               | agreementTypeData/phaseOfStudy/hrn          | agreementTypeData/sponsorProtocolNumber | agreementTypeData/protocolTitle | agreementTypeData/protocolDocument/url                            | agreementTypeData/consentFormsDocuments/0/url                     | agreementTypeData/isReimbursementTobeProvided | agreementTypeData/willUseCro | agreementTypeData/cro/hrn | agreementTypeData/croOther | agreementTypeData/croContactsOther/1/person/hrn | agreementTypeData/croContactsOther/2/person/hrn | agreementTypeData/croContactsOther/2/contactName | agreementTypeData/croContactsOther/2/contactPhone | agreementTypeData/croContactsOther/2/contactEmail | agreementTypeData/croContactPrimary/person/hrn | agreementTypeData/doesThisInvolveSubrecipients | agreementTypeData/subrecipientsOrganizations | agreementTypeData/ctaMaterials/0/materialType/hrn | agreementTypeData/ctaMaterials/0/useInTrial/hrn | agreementTypeData/ctaMaterials/0/provider | agreementTypeData/ctaMaterials/0/materialDescription | agreementTypeData/doesThisInvolveOtherMaterials | agreementTypeData/ctaMaterialsOther/0/materialType/hrn | agreementTypeData/ctaMaterialsOther/0/provider | agreementTypeData/ctaMaterialsOther/0/materialDescription | agreementTypeData/isStudyPartOfCooperativeGroup |
        | hrn:hrs:lists:agrmt-types/CTA | hrn:hrs:lists:agrmt-cta-type-trial/inv-init-otr-inst | hrn:hrs:lists:agrmt-cta-phase-study/phase-2 | Z123EF                            | Wyeth ZZ784                     | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | false                                         | true                         | hrn:hrs:orgs:33           | test                       | hrn:hrs:persons:801                             | hrn:hrs:persons:811                             | contact2                                         | 044-1234567                                       | contactEmail@huron.com                            | hrn:hrs:persons:801                            | null                                  | null                                | hrn:hrs:lists:agrmt-cta-material-type/device      | hrn:hrs:lists:agrmt-cta-use-in-trial/standard-of-care  | provider1                                 | materialDescription12                                | true                                            | hrn:hrs:lists:agrmt-cta-material-type-other/equipment    | provider1                                      | materialDescription                                       | true                                            |
          When I perform Put request for Agreements
	 Then I validate status code for Put requests
      And I Validate "agreementType/hrn" attribute for Agreements
      And I Validate "agreementTypeData/typeOfTrial/hrn" attribute for Agreements
        And I Validate "agreementTypeData/phaseOfStudy/hrn" attribute for Agreements
        And I Validate "agreementTypeData/sponsorProtocolNumber" attribute for Agreements
        And I Validate "agreementTypeData/protocolTitle" attribute for Agreements
        And I Validate "agreementTypeData/isReimbursementTobeProvided" attribute for Agreements
        And I Validate "agreementTypeData/willUseCro" attribute for Agreements
        And I Validate "agreementTypeData/croOther" attribute for Agreements
       And I Validate "agreementTypeData/croContactsOther/1/person/hrn" attribute for Agreements
       And I Validate "agreementTypeData/croContactPrimary/person/hrn" attribute for Agreements
       And I Validate "agreementTypeData/ctaMaterials/0/materialType/hrn" attribute for Agreements
       And I Validate "agreementTypeData/ctaMaterials/0/useInTrial/hrn" attribute for Agreements
       And I Validate "agreementTypeData/doesThisInvolveOtherMaterials" attribute for Agreements
     And I Validate "agreementTypeData/isStudyPartOfCooperativeGroup" attribute for Agreements

         

         ## ********************* PATCH REQUEST *********************************
Scenario: AGR_006_08_ValidateAgreementsAPI_CTA-TypeOfTrail-InvestigatorInitiatedAtAnotherInstitution_PatchRequest

   Given I Set UP URL For APIs with Endpoint as "/api/agreements"
    When I retrieve data using unique key by Get Request for Agreements
    | hrn      |
    | hrn:hrs:agreements:797 |
    When I create payload for Patch request
   | agreementType/hrn               | agreementTypeData/typeOfTrial/hrn               | agreementTypeData/phaseOfStudy/hrn          | agreementTypeData/sponsorProtocolNumber | agreementTypeData/protocolTitle | agreementTypeData/protocolDocument/url                            | agreementTypeData/consentFormsDocuments/0/url                     | agreementTypeData/isReimbursementTobeProvided | agreementTypeData/willUseCro | agreementTypeData/cro/hrn | agreementTypeData/croOther | agreementTypeData/croContactsOther/1/person/hrn | agreementTypeData/croContactsOther/2/person/hrn | agreementTypeData/croContactsOther/2/contactName | agreementTypeData/croContactsOther/2/contactPhone | agreementTypeData/croContactsOther/2/contactEmail | agreementTypeData/croContactPrimary/person/hrn | agreementTypeData/doesThisInvolveSubrecipients | agreementTypeData/subrecipientsOrganizations | agreementTypeData/ctaMaterials/0/materialType/hrn | agreementTypeData/ctaMaterials/0/useInTrial/hrn | agreementTypeData/ctaMaterials/0/provider | agreementTypeData/ctaMaterials/0/materialDescription | agreementTypeData/doesThisInvolveOtherMaterials | agreementTypeData/ctaMaterialsOther/0/materialType/hrn | agreementTypeData/ctaMaterialsOther/0/provider | agreementTypeData/ctaMaterialsOther/0/materialDescription | agreementTypeData/isStudyPartOfCooperativeGroup |
   | hrn:hrs:lists:agrmt-types/CTA | hrn:hrs:lists:agrmt-cta-type-trial/inv-init-otr-inst | hrn:hrs:lists:agrmt-cta-phase-study/phase-4 | Z123EF                            | Wyeth ZZ784                     | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | false                                         | true                         | hrn:hrs:orgs:33           | test                       | hrn:hrs:persons:801                             | hrn:hrs:persons:811                             | contact2                                         | 044-1234567                                       | contactEmail@huron.com                            | hrn:hrs:persons:801                            | null                                  | null                                | hrn:hrs:lists:agrmt-cta-material-type/device      | hrn:hrs:lists:agrmt-cta-use-in-trial/research  | provider1                                 | materialDescription12                                | true                                            | hrn:hrs:lists:agrmt-cta-material-type-other/other    | provider1                                      | materialDescription                                       | true                                            |      
   	When I perform Patch request for Agreements
	Then I validate status code for Patch request
      And I Validate "agreementType/hrn" attribute for Agreements
      And I Validate "agreementTypeData/typeOfTrial/hrn" attribute for Agreements
        And I Validate "agreementTypeData/phaseOfStudy/hrn" attribute for Agreements
        And I Validate "agreementTypeData/sponsorProtocolNumber" attribute for Agreements
        And I Validate "agreementTypeData/protocolTitle" attribute for Agreements
        And I Validate "agreementTypeData/isReimbursementTobeProvided" attribute for Agreements
        And I Validate "agreementTypeData/willUseCro" attribute for Agreements
        And I Validate "agreementTypeData/croOther" attribute for Agreements
       And I Validate "agreementTypeData/croContactsOther/1/person/hrn" attribute for Agreements
       And I Validate "agreementTypeData/croContactPrimary/person/hrn" attribute for Agreements
       And I Validate "agreementTypeData/ctaMaterials/0/materialType/hrn" attribute for Agreements
       And I Validate "agreementTypeData/ctaMaterials/0/useInTrial/hrn" attribute for Agreements
       And I Validate "agreementTypeData/doesThisInvolveOtherMaterials" attribute for Agreements
       And I Validate "agreementTypeData/isStudyPartOfCooperativeGroup" attribute for Agreements

       ## ********************* Error Messages Validations *********************************
       Scenario: AGR_006_09_ErrorMessagesValidationsForCTA-API

         #Payload when  required field "typeOfTrial" is missing in CTA API
          When I generate payload of Agreements for Post request for CTA API
        | title                  | firstDraftTobeGeneratedInternally | principalInvestigator/hrn | primaryContact/hrn  | agreementType/hrn             | responsibleUnit/hrn | counterParties/0/organization/hrn | counterParties/0/person/hrn | agreementTypeData/phaseOfStudy/hrn          | agreementTypeData/sponsorProtocolNumber | agreementTypeData/protocolTitle | agreementTypeData/protocolDocument/url                            | agreementTypeData/consentFormsDocuments/0/url                     | agreementTypeData/isReimbursementTobeProvided | agreementTypeData/willUseCro | agreementTypeData/cro/hrn | agreementTypeData/croOther | agreementTypeData/croContactsOther/1/person/hrn | agreementTypeData/croContactsOther/2/person/hrn | agreementTypeData/croContactsOther/2/contactName | agreementTypeData/croContactsOther/2/contactPhone | agreementTypeData/croContactsOther/2/contactEmail | agreementTypeData/croContactPrimary/person/hrn | agreementTypeData/doesThisInvolveSubrecipients | agreementTypeData/subrecipientsOrganizations  | agreementTypeData/ctaMaterials/0/materialType/hrn | agreementTypeData/ctaMaterials/0/useInTrial/hrn | agreementTypeData/ctaMaterials/0/provider | agreementTypeData/ctaMaterials/0/materialDescription | agreementTypeData/doesThisInvolveOtherMaterials | agreementTypeData/ctaMaterialsOther/0/materialType/hrn | agreementTypeData/ctaMaterialsOther/0/provider | agreementTypeData/ctaMaterialsOther/0/materialDescription | agreementTypeData/isStudyPartOfCooperativeGroup |
        | Agreement MTA Test 514 | true                              | hrn:hrs:persons:801       | hrn:hrs:persons:301 | hrn:hrs:lists:agrmt-types/CTA | hrn:hrs:orgs:309    | hrn:hrs:orgs:3                    | hrn:hrs:persons:301          | hrn:hrs:lists:agrmt-cta-phase-study/phase-1 | FF720W                                  | Wyeth ZZ784                     | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | false                                         | true                         | hrn:hrs:orgs:33           | test                       | hrn:hrs:persons:801                             | hrn:hrs:persons:811                             | contact2                                         | 044-1234567                                       | contactEmail@huron.com                            | hrn:hrs:persons:801                            | null                                         | null                                            | hrn:hrs:lists:agrmt-cta-material-type/other       | hrn:hrs:lists:agrmt-cta-use-in-trial/research   | provider1                                 | materialDescription12                                | true                                            | hrn:hrs:lists:agrmt-cta-material-type-other/other      | provider1                                      | materialDescription                                       | true                                            |
        When I perform Post request for Agreements
        Then I Validate the error message for missing required field typeOfTrial in post request
        Then I verify the resource is not created

         #Payload when  field "typeOfTrial" as hrn associated with radiobutton "InitiatedAtOurInstitution"  then sponsorProtocolNumber field is invalid
         When I generate payload of Agreements for Post request for CTA API
        | title                  | firstDraftTobeGeneratedInternally | principalInvestigator/hrn | primaryContact/hrn  | agreementType/hrn             | responsibleUnit/hrn | counterParties/0/organization/hrn | counterParties/0/person/hrn | agreementTypeData/typeOfTrial/hrn               | agreementTypeData/phaseOfStudy/hrn          | agreementTypeData/sponsorProtocolNumber | agreementTypeData/protocolTitle | agreementTypeData/protocolDocument/url                            | agreementTypeData/consentFormsDocuments/0/url                     | agreementTypeData/isReimbursementTobeProvided | agreementTypeData/willUseCro | agreementTypeData/cro/hrn | agreementTypeData/croOther | agreementTypeData/croContactsOther/1/person/hrn | agreementTypeData/croContactsOther/2/person/hrn | agreementTypeData/croContactsOther/2/contactName | agreementTypeData/croContactsOther/2/contactPhone | agreementTypeData/croContactsOther/2/contactEmail | agreementTypeData/croContactPrimary/person/hrn | agreementTypeData/doesThisInvolveSubrecipients | agreementTypeData/subrecipientsOrganizations | agreementTypeData/ctaMaterials/0/materialType/hrn | agreementTypeData/ctaMaterials/0/useInTrial/hrn | agreementTypeData/ctaMaterials/0/provider | agreementTypeData/ctaMaterials/0/materialDescription | agreementTypeData/doesThisInvolveOtherMaterials | agreementTypeData/ctaMaterialsOther/0/materialType/hrn | agreementTypeData/ctaMaterialsOther/0/provider | agreementTypeData/ctaMaterialsOther/0/materialDescription | agreementTypeData/isStudyPartOfCooperativeGroup |
        | Agreement MTA Test 514 | true                              | hrn:hrs:persons:801       | hrn:hrs:persons:301 | hrn:hrs:lists:agrmt-types/CTA | hrn:hrs:orgs:309    | hrn:hrs:orgs:3                    | hrn:hrs:persons:301         | hrn:hrs:lists:agrmt-cta-type-trial/inv-init-inst | hrn:hrs:lists:agrmt-cta-phase-study/phase-4 | SPN001                              | Wyeth ZZ784                     | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | false                                         | true                         | hrn:hrs:orgs:33           | test                       | hrn:hrs:persons:801                             | hrn:hrs:persons:811                             | contact2                                         | 044-1234567                                       | contactEmail@huron.com                            | hrn:hrs:persons:801                            | null                                     | null                                  | hrn:hrs:lists:agrmt-cta-material-type/device      | hrn:hrs:lists:agrmt-cta-use-in-trial/standard-of-care  | provider1                                 | materialDescription12                                | true                                            | hrn:hrs:lists:agrmt-cta-material-type-other/equipment    | provider1                                      | materialDescription                                       | true                                            |
        When I perform Post request for Agreements
        Then I Validate the error message for invalid  field sponsorProtocolNumber when typeOfTrial as hrn associated with radiobutton InitiatedAtOurInstitution
        Then I verify the resource is not created

        #Payload when willUseCro field is marked false then field CRO is invalid
         When I generate payload of Agreements for Post request for CTA API
       | title                  | firstDraftTobeGeneratedInternally | principalInvestigator/hrn | primaryContact/hrn  | agreementType/hrn             | responsibleUnit/hrn | counterParties/0/organization/hrn | counterParties/0/person/hrn | agreementTypeData/typeOfTrial/hrn         | agreementTypeData/phaseOfStudy/hrn          | agreementTypeData/sponsorProtocolNumber | agreementTypeData/protocolTitle | agreementTypeData/protocolDocument/url                            | agreementTypeData/consentFormsDocuments/0/url                     | agreementTypeData/isReimbursementTobeProvided | agreementTypeData/willUseCro | agreementTypeData/cro/hrn | agreementTypeData/croOther | agreementTypeData/croContactsOther | agreementTypeData/croContactPrimary | agreementTypeData/doesThisInvolveSubrecipients | agreementTypeData/subrecipientsOrganizations | agreementTypeData/ctaMaterials/0/materialType/hrn | agreementTypeData/ctaMaterials/0/useInTrial/hrn | agreementTypeData/ctaMaterials/0/provider | agreementTypeData/ctaMaterials/0/materialDescription | agreementTypeData/doesThisInvolveOtherMaterials | agreementTypeData/ctaMaterialsOther/0/materialType/hrn | agreementTypeData/ctaMaterialsOther/0/provider | agreementTypeData/ctaMaterialsOther/0/materialDescription | agreementTypeData/isStudyPartOfCooperativeGroup |
       | Agreement MTA Test 514 | true                              | hrn:hrs:persons:801       | hrn:hrs:persons:301 | hrn:hrs:lists:agrmt-types/CTA | hrn:hrs:orgs:309    | hrn:hrs:orgs:3                    | hrn:hrs:persons:301         | hrn:hrs:lists:agrmt-cta-type-trial/ind-sp | hrn:hrs:lists:agrmt-cta-phase-study/phase-1 | FF720W                                  | Wyeth ZZ784                     | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | false                                         | false                        | hrn:hrs:orgs:33           | null                      | null                               | null                                           | null                                           |null                   | hrn:hrs:lists:agrmt-cta-material-type/other       | hrn:hrs:lists:agrmt-cta-use-in-trial/research   | provider1                                 | materialDescription12                                | true                                            | hrn:hrs:lists:agrmt-cta-material-type-other/other      | provider1                                      | materialDescription                                       | true                                            |
        When I perform Post request for Agreements
        Then I Validate the error message for invalid  field CRO  when willUseCro field is marked false
        Then I verify the resource is not created

        #Payload when  field "willUseCro" is marked false then fields croContactsOther is invalid
         When I generate payload of Agreements for Post request for CTA API
          | title                  | firstDraftTobeGeneratedInternally | principalInvestigator/hrn | primaryContact/hrn  | agreementType/hrn             | responsibleUnit/hrn | counterParties/0/organization/hrn | counterParties/0/person/hrn | agreementTypeData/typeOfTrial/hrn         | agreementTypeData/phaseOfStudy/hrn          | agreementTypeData/sponsorProtocolNumber | agreementTypeData/protocolTitle | agreementTypeData/protocolDocument/url                            | agreementTypeData/consentFormsDocuments/0/url                     | agreementTypeData/isReimbursementTobeProvided | agreementTypeData/willUseCro | agreementTypeData/cro/hrn | agreementTypeData/croOther | agreementTypeData/croContactsOther/1/person/hrn | agreementTypeData/croContactsOther/2/person/hrn | agreementTypeData/croContactsOther/2/contactName | agreementTypeData/croContactsOther/2/contactPhone | agreementTypeData/croContactsOther/2/contactEmail | agreementTypeData/croContactPrimary | agreementTypeData/doesThisInvolveSubrecipients | agreementTypeData/subrecipientsOrganizations  | agreementTypeData/ctaMaterials/0/materialType/hrn | agreementTypeData/ctaMaterials/0/useInTrial/hrn | agreementTypeData/ctaMaterials/0/provider | agreementTypeData/ctaMaterials/0/materialDescription | agreementTypeData/doesThisInvolveOtherMaterials | agreementTypeData/ctaMaterialsOther/0/materialType/hrn | agreementTypeData/ctaMaterialsOther/0/provider | agreementTypeData/ctaMaterialsOther/0/materialDescription | agreementTypeData/isStudyPartOfCooperativeGroup |
        | Agreement MTA Test 514 | true                              | hrn:hrs:persons:801       | hrn:hrs:persons:301 | hrn:hrs:lists:agrmt-types/CTA | hrn:hrs:orgs:309    | hrn:hrs:orgs:3                    | hrn:hrs:persons:301         | hrn:hrs:lists:agrmt-cta-type-trial/ind-sp | hrn:hrs:lists:agrmt-cta-phase-study/phase-1 | FF720W                                  | Wyeth ZZ784                     | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | false                                         | false                         | null       | null                       | hrn:hrs:persons:801                             | hrn:hrs:persons:811                             | contact2                                         | 044-1234567                                       | contactEmail@huron.com                            | null                         | null                                         | null                                            | hrn:hrs:lists:agrmt-cta-material-type/other       | hrn:hrs:lists:agrmt-cta-use-in-trial/research   | provider1                                 | materialDescription12                                | true                                            | hrn:hrs:lists:agrmt-cta-material-type-other/other      | provider1                                      | materialDescription                                       | true                                            |
        When I perform Post request for Agreements
        Then I Validate the error message for invalid  field croContactsOther  when willUseCro field is marked false
        Then I verify the resource is not created

       #Payload when  field "willUseCro" is marked false then fields croOther is invalid
         When I generate payload of Agreements for Post request for CTA API
        | title             | firstDraftTobeGeneratedInternally | principalInvestigator/hrn | primaryContact/hrn  | agreementType/hrn             | responsibleUnit/hrn | counterParties/0/organization/hrn | counterParties/0/person/hrn | agreementTypeData/typeOfTrial/hrn               | agreementTypeData/phaseOfStudy/hrn          | agreementTypeData/sponsorProtocolNumber | agreementTypeData/protocolTitle | agreementTypeData/protocolDocument/url                            | agreementTypeData/consentFormsDocuments/0/url                     | agreementTypeData/isReimbursementTobeProvided | agreementTypeData/willUseCro | agreementTypeData/cro/hrn | agreementTypeData/croOther | agreementTypeData/croContactsOther| agreementTypeData/croContactPrimary | agreementTypeData/doesThisInvolveSubrecipients | agreementTypeData/subrecipientsOrganizations| agreementTypeData/ctaMaterials/0/materialType/hrn | agreementTypeData/ctaMaterials/0/useInTrial/hrn | agreementTypeData/ctaMaterials/0/provider | agreementTypeData/ctaMaterials/0/materialDescription | agreementTypeData/doesThisInvolveOtherMaterials | agreementTypeData/ctaMaterialsOther/0/materialType/hrn | agreementTypeData/ctaMaterialsOther/0/provider | agreementTypeData/ctaMaterialsOther/0/materialDescription | agreementTypeData/isStudyPartOfCooperativeGroup |
        | Agreement MTA Test 514 | true                              | hrn:hrs:persons:801       | hrn:hrs:persons:301 | hrn:hrs:lists:agrmt-types/CTA | hrn:hrs:orgs:309    | hrn:hrs:orgs:3                    | hrn:hrs:persons:301         | hrn:hrs:lists:agrmt-cta-type-trial/ind-sp | hrn:hrs:lists:agrmt-cta-phase-study/phase-4 | null                           | Wyeth ZZ784                     | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | false                                         | false                        | null           | hrn:hrs:persons:301                  | null                                | null                                      | null                                       | null                                  | hrn:hrs:lists:agrmt-cta-material-type/device      | hrn:hrs:lists:agrmt-cta-use-in-trial/standard-of-care  | provider1                                 | materialDescription12                                | true                                            | hrn:hrs:lists:agrmt-cta-material-type-other/equipment    | provider1                                      | materialDescription                                       | true                                            | 
        When I perform Post request for Agreements
        Then I Validate the error message for invalid  field croOther  when willUseCro field is marked false
        Then I verify the resource is not created

       #Payload when  field "willUseCro" is marked false then fields croContactPrimary is invalid
         When I generate payload of Agreements for Post request for CTA API
       | title                  | firstDraftTobeGeneratedInternally | principalInvestigator/hrn | primaryContact/hrn  | agreementType/hrn             | responsibleUnit/hrn | counterParties/0/organization/hrn | counterParties/0/person/hrn | agreementTypeData/typeOfTrial/hrn               | agreementTypeData/phaseOfStudy/hrn          | agreementTypeData/sponsorProtocolNumber | agreementTypeData/protocolTitle | agreementTypeData/protocolDocument/url                            | agreementTypeData/consentFormsDocuments/0/url      | agreementTypeData/isReimbursementTobeProvided | agreementTypeData/willUseCro | agreementTypeData/cro/hrn | agreementTypeData/croOther | agreementTypeData/croContactsOther|agreementTypeData/croContactPrimary/person/hrn | agreementTypeData/doesThisInvolveSubrecipients | agreementTypeData/subrecipientsOrganizations/0/organization/hrn | agreementTypeData/ctaMaterials/0/materialType/hrn | agreementTypeData/ctaMaterials/0/useInTrial/hrn | agreementTypeData/ctaMaterials/0/provider | agreementTypeData/ctaMaterials/0/materialDescription | agreementTypeData/doesThisInvolveOtherMaterials | agreementTypeData/ctaMaterialsOther/0/materialType/hrn | agreementTypeData/ctaMaterialsOther/0/provider | agreementTypeData/ctaMaterialsOther/0/materialDescription | agreementTypeData/isStudyPartOfCooperativeGroup |
       | Agreement MTA Test 514 | true                             | hrn:hrs:persons:801       | hrn:hrs:persons:301 | hrn:hrs:lists:agrmt-types/CTA | hrn:hrs:orgs:309    | hrn:hrs:orgs:3                    | hrn:hrs:persons:301         | hrn:hrs:lists:agrmt-cta-type-trial/inv-init-otr-inst | hrn:hrs:lists:agrmt-cta-phase-study/phase-4 | null                            | Wyeth ZZ784                     | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | https://agreementdocs.s3.us-east-2.amazonaws.com/angiogenesis.pdf | false                                         | false                        | null           | null                       | null                                |                   hrn:hrs:persons:801                 | true                                       | hrn:hrs:orgs:3                                    | hrn:hrs:lists:agrmt-cta-material-type/device      | hrn:hrs:lists:agrmt-cta-use-in-trial/standard-of-care  | provider1                                 | materialDescription12                                | true                                            | hrn:hrs:lists:agrmt-cta-material-type-other/equipment    | provider1                                      | materialDescription                                       | true                                            | 
        When I perform Post request for Agreements
        Then I Validate the error message for invalid field croContactPrimary when willUseCro field is marked false
        Then I verify the resource is not created